# Generated by Django 3.2.4 on 2021-06-17 04:05

import aecb.api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('birthdate', models.DateField()),
                ('income', models.IntegerField()),
                ('has_credit', models.BooleanField()),
                ('active', models.BooleanField()),
                ('address', models.CharField(max_length=50)),
                ('neighborhood', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('min_credit', models.IntegerField()),
                ('max_credit', models.IntegerField()),
                ('tier', models.SmallIntegerField()),
                ('image', models.ImageField(upload_to=aecb.api.models.upload_to)),
                ('cat', models.SmallIntegerField()),
                ('annual_fee', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('name', models.CharField(max_length=60)),
                ('rfc', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('max_protection', models.IntegerField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PreapprovalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.client')),
                ('credit_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.creditcard')),
                ('reviewed_by', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.employee')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('description', models.CharField(max_length=256)),
                ('valid_until', models.DateField()),
                ('last_update', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_ratio', models.FloatField(default=0.0)),
                ('approval_ratio', models.FloatField(default=0.0)),
                ('most_requested', models.CharField(default=None, max_length=60)),
                ('most_approved', models.CharField(default=None, max_length=60)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.CharField(max_length=128, null=True)),
                ('clients', models.ManyToManyField(blank=True, to='api.Client')),
                ('employees', models.ManyToManyField(blank=True, to='api.Employee')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_by', to='api.employee')),
                ('requests', models.ManyToManyField(to='api.PreapprovalRequest')),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='insurances',
            field=models.ManyToManyField(blank=True, to='api.Insurance'),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='promotions',
            field=models.ManyToManyField(blank=True, to='api.Promotion'),
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=60)),
                ('token', models.CharField(max_length=1200)),
                ('user_email', models.CharField(max_length=60)),
                ('last_signin', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
